"""
Role chains: composition, aliasing, and the guarantees they must not lose.

Offline. The point of these is that a routing preference is a *preference* —
it must never become a filter that can starve a role, and it must never
silently name a model that does not exist.
"""

from __future__ import annotations

import pytest

from oe_max.providers.registry import Registry, build_default_registry
from oe_max.roles import (
    ALIASES, PRIMARY_ALIAS, Role, build_chains, preferences, role_for_alias,
    validate_preferences,
)
from oe_max.router import DEFAULT_CHAIN, Router


def _registry_routes():
    reg = build_default_registry()
    return [(pname, key) for pname, p in reg.items() for key in p.models]


def test_every_preferred_route_exists_in_the_registry():
    """
    A preference naming a withdrawn or renamed model degrades silently: the
    entry is skipped and the role quietly runs on its tail, which looks like a
    working system doing the wrong thing.

    This is not hypothetical. The chains in `control_plane` named
    `deepseek-ai/deepseek-v4-pro` and `qwen/qwen2.5-coder-32b-instruct` for
    months; neither is in NVIDIA's catalogue, so the "strong fallback" could
    never have served a single request.
    """
    missing = validate_preferences(_registry_routes())
    assert missing == {}, f"preferences name routes that do not exist: {missing}"


def test_no_role_can_be_starved():
    """
    Preference is an ordering, never a permission. Every role must be able to
    reach every configured route, or one provider outage turns into a dead
    role while usable capacity sits idle.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role in Role:
        assert set(DEFAULT_CHAIN) <= set(chains[role]), (
            f"{role.value} cannot reach every route")


def test_a_chain_never_repeats_a_route():
    """A duplicate would spend two attempts of the budget on one model."""
    for role, chain in build_chains(DEFAULT_CHAIN).items():
        assert len(chain) == len(set(chain)), f"{role.value} repeats a route"


def test_preferences_lead_their_chain():
    """The whole point: the preferred routes come first, in order."""
    chains = build_chains(DEFAULT_CHAIN)
    for role, preferred in preferences().items():
        assert chains[role][:len(preferred)] == preferred, role.value


# The two tests below pin a *principle*, not a vendor: latency-bound roles must
# not lead with a model that thinks before answering, and reasoning-bound roles
# must not lead with the cheap fast one. They were written against the Zen table
# and are now expressed against the NIM-first one, because the operator moved
# the primary to NVIDIA NIM on 2026-08-27. The principle survived the move; if a
# future reordering breaks these, that reordering needs an argument.
_FAST_ROUTE = ("nvidia_nim", "nemotron_super_120b")
_REASONING_ROUTES = {("nvidia_nim", "nemotron_ultra_253b"),
                     ("nvidia_nim", "kimi_k3")}


def test_the_judge_and_fast_roles_lead_with_the_cheapest_fastest_route():
    """
    `nemotron-3-super-120b-a12b` answered in 732 ms with tools on 2026-08-28 —
    the fastest working route measured on any provider here, free or paid.

    Ranking and clerical work do not need a flagship reasoner, so routing them
    to one buys latency and truncation risk and nothing else. That was true when
    the cheap route was Zen's laguna at 1.6 s against nemotron-ultra's 3.3 s, and
    it is true now with a wider gap.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role in (Role.JUDGE, Role.FAST):
        assert chains[role][0] == _FAST_ROUTE, role.value


def test_the_reasoning_roles_do_not_lead_with_the_fast_route():
    """
    The converse, and the one that actually costs quality when broken: a
    mutation generated by the cheap route is a worse mutation.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role in (Role.REASONER, Role.CODER):
        assert chains[role][0] in _REASONING_ROUTES, role.value
        assert chains[role][0] != _FAST_ROUTE, role.value


def test_nvidia_nim_leads_every_role():
    """
    Operator decision, 2026-08-27: NIM is the primary provider.

    It is also the only provider here whose models were probed individually with
    a real key (docs/project/handoff.md §4i), which is why it leads rather than merely appearing.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role, chain in chains.items():
        assert chain[0][0] == "nvidia_nim", f"{role.value} leads with {chain[0]}"


def test_every_role_still_has_a_keyless_fallback():
    """
    NIM needs NVIDIA_API_KEY. Leading with it is only safe because a route whose
    credential is absent is filtered out rather than attempted -- so every chain
    must still contain a keyless Zen route behind the NIM ones, or a checkout
    with no key would have nothing left to serve from.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role, chain in chains.items():
        assert any(provider == "opencode_zen" for provider, _ in chain), role.value


def test_ox_alpha_is_absent_from_every_chain():
    """
    Ox Alpha was withdrawn by the provider on 2026-08-26 and taken out of
    service here entirely on 2026-08-27. Two routes pointed at it -- Zen's
    `x-preview-f-free` and an alternate `stealth/ox-alpha` through OpenRouter --
    and the second outlived the first by a day because only the first was
    obvious. This fails if either comes back.
    """
    chains = build_chains(DEFAULT_CHAIN)
    for role, chain in chains.items():
        for provider, model in chain:
            assert "ox" != model.split("_")[0], f"{role.value}: {provider}/{model}"
            assert "ox_alpha" != model, f"{role.value}: {provider}/{model}"


@pytest.mark.parametrize("alias,expected", sorted(
    (a, r.value) for a, r in ALIASES.items()))
def test_each_alias_selects_its_role(alias, expected):
    assert role_for_alias(alias).value == expected


def test_the_engine_alias_still_means_mutation_generation():
    """
    `oe-max-primary` is what every shipped config names. Repointing it would
    silently change what existing runs do, and every measurement already
    recorded would stop being comparable.
    """
    assert role_for_alias(PRIMARY_ALIAS) is Role.REASONER


def test_an_unknown_model_name_is_served_rather_than_refused():
    """A client that has not been told about the aliases must still work."""
    assert role_for_alias("gpt-4") is Role.REASONER
    assert role_for_alias("") is Role.REASONER


def test_a_custom_chain_produces_consistent_role_chains():
    """
    Customising `chain` must not leave the role chains pointing at the shipped
    defaults — that would give an operator a configuration whose roles ignore
    their own edit.
    """
    custom = [("opencode_zen", "hy3")]
    router = Router(Registry(build_default_registry()), chain=custom)
    for role in Role:
        assert ("opencode_zen", "hy3") in router.chains[role], role.value


def test_withdrawn_models_are_not_in_the_default_chain():
    """
    Ox Alpha stayed at the head of the chain after it stopped existing, and
    every request paid for it. Nothing believed unavailable belongs in the
    shipped ordering.
    """
    reg = build_default_registry()
    for provider_name, model_key in DEFAULT_CHAIN:
        spec = reg[provider_name].models[model_key]
        assert spec.available is not False, (
            f"{provider_name}/{spec.id} is in the default chain but is "
            f"believed unavailable: {spec.notes}")


def test_the_snapshot_reports_what_each_role_would_actually_reach():
    """
    The chain is the intent; `serving` is the outcome. They differ exactly when
    something is unhealthy — which is when an operator looks at this.
    """
    from oe_max.providers.registry import Registry, build_default_registry

    snap = Router(Registry(build_default_registry())).snapshot()

    assert set(snap["roles"]) == {r.value for r in Role}
    for role, info in snap["roles"].items():
        assert info["chain"], f"{role} has an empty chain"
        # Every free Zen route serves without a credential, so with no keys at
        # all every role must still have somewhere to go. A role that cannot
        # serve while others can is invisible in an aggregate route table.
        assert info["serving"], f"{role} has nothing serving"


def test_a_role_with_nothing_serving_is_reported_rather_than_omitted():
    """
    Reporting `serving: None` is the point. Omitting the role would make a
    completely dead role look identical to a healthy one at a glance.
    """
    from oe_max.providers.registry import Registry, build_default_registry

    reg = Registry(build_default_registry())
    for provider in reg.providers.values():
        provider.enabled = False

    snap = Router(reg).snapshot()

    for role, info in snap["roles"].items():
        assert info["serving"] is None, role
        assert info["excluded"], f"{role} explains nothing about why"


def test_the_mutation_roles_lead_with_a_reasoning_route_that_answers():
    """Two constraints at once, and the first one outranks the second.

    The 120B is the quickest route here and is deliberately ineligible to lead a
    mutation role -- a mutation generated by the cheap route is a worse
    mutation, which the invariant above enforces. Speed that costs mutation
    quality is not efficiency, and this test exists because reordering for
    latency is the tempting mistake.

    Among the routes that *are* eligible, lead with the one that answers.
    kimi-k3 led until its allowance was measured on 2026-08-29: about ten calls
    exhausted it, after which it refused in 0.2s while three nemotron routes
    returned 200 in the same minute. Failover covered it -- verified, attempt 2
    -- but at one wasted attempt of four per request. The flagship answered
    every time it was asked.
    """
    for role in (Role.REASONER, Role.CODER):
        head = preferences()[role][0]
        assert head == ("nvidia_nim", "nemotron_ultra_253b"), role
        assert head != _FAST_ROUTE, role


def test_the_slow_deepseek_is_not_on_any_chain():
    """It serves, so nothing else would exclude it -- only its latency does.

    183.5s on a one-word prompt is 115x kimi-k3. It stays configured and
    disabled rather than deleted, so this checks it is absent from the
    *preferences* rather than from the registry.
    """
    for role, chain in preferences().items():
        assert ("nvidia_nim", "deepseek_v4_pro") not in chain, role


def test_the_disabled_deepseek_is_recorded_rather_than_deleted():
    """A model excluded by judgement should say so where the next person looks,
    or they configure it again and wonder why it was left out."""
    from oe_max.providers.registry import build_default_registry

    nim = build_default_registry()["nvidia_nim"]
    spec = nim.models.get("deepseek_v4_pro")
    assert spec is not None, "deepseek_v4_pro was deleted rather than disabled"
    assert spec.available is False
    assert "183" in spec.notes, "the measurement that excluded it is not recorded"


def test_kimi_k3_is_still_second_on_both_chains():
    """Second, not dropped. It is the better model when its allowance permits,
    it is roughly twice as quick as the flagship when serving, and single-model
    mode can pin it outright."""
    for role in (Role.REASONER, Role.CODER):
        assert preferences()[role][1] == ("nvidia_nim", "kimi_k3"), role
