"""
Candidates per model request — the number multi-offspring exists to move.

The distinction that matters is between *candidates* and *useful* candidates. A
response containing three alternatives that all collapse to the same AST is one
candidate that cost a request and a half; counting it as three would make the
feature look like it worked. So the headline is the useful rate, and the raw
rate is reported next to it precisely so the gap between them is visible.

"Useful" here means **distinct code that entered the population**. Two choices
are folded into that, and both were forced by a measurement:

* Not "it improved the champion". In a quality-diversity search a candidate
  that widens the archive has value even when it loses to the incumbent, and
  counting only improvements makes every feature look useless late in a run,
  when improvements are rare by construction.

* Not "it was not rejected by the novelty gate". The first local run at N=3
  produced 29 candidates from 12 requests with **zero** rejections — and only
  10 distinct code hashes among them. Trusting the gate's own count would have
  reported a 2.4x gain from a run where two-thirds of the output was duplicate
  code. Distinctness is measured directly, from the hashes, rather than
  inferred from whether something else noticed.
"""

from __future__ import annotations

import sqlite3
from typing import Any, Dict, List, Optional

MUTATION_ROLE = "mutation"


def measure(conn: sqlite3.Connection, run_id: str) -> Dict[str, Any]:
    """Yield per request for one run."""
    conn.row_factory = sqlite3.Row

    requests = conn.execute(
        "SELECT COUNT(*) FROM model_requests WHERE run_id = ? "
        "  AND (role = ? OR role IS NULL)", (run_id, MUTATION_ROLE)).fetchone()[0]

    row = conn.execute(
        "SELECT COUNT(*) AS total, "
        "       SUM(CASE WHEN json_extract(metadata, '$.multi_offspring') = 1 "
        "                THEN 1 ELSE 0 END) AS extra_offspring, "
        "       SUM(CASE WHEN json_extract(metadata, '$.migrant') = 1 "
        "                THEN 1 ELSE 0 END) AS migrants "
        "  FROM candidates WHERE run_id = ?", (run_id,)).fetchone()

    # Migrants are copies of candidates already counted, and the seed program
    # was not generated by any request. Leaving either in would credit the
    # model for work it did not do.
    generated, distinct = _generated(conn, run_id)

    rejected = conn.execute(
        "SELECT COUNT(*) FROM events WHERE run_id = ? AND type = 'candidate.rejected'",
        (run_id,)).fetchone()[0]

    total = int(row["total"] or 0)
    extra = int(row["extra_offspring"] or 0)
    migrants = int(row["migrants"] or 0)

    def per_request(n: int) -> Optional[float]:
        return round(n / requests, 3) if requests else None

    return {
        "mutation_requests": int(requests or 0),
        "candidates": total,
        "generated_candidates": generated,
        "distinct_generated": distinct,
        "extra_offspring": extra,
        "migrants": migrants,
        "rejected_duplicates": rejected,
        # The gap between these two is the whole story: raw yield that is not
        # distinct is throughput that is not real.
        "candidates_per_request": per_request(generated),
        "useful_candidates_per_request": per_request(distinct),
        "duplicate_share": (round(1 - distinct / generated, 3) if generated else None),
    }


def _generated(conn: sqlite3.Connection, run_id: str) -> tuple:
    """(generated candidates, how many of them are distinct code)."""
    row = conn.execute(
        "SELECT COUNT(*) AS n, COUNT(DISTINCT code_hash) AS d FROM candidates "
        " WHERE run_id = ? AND parent_id IS NOT NULL "
        "   AND COALESCE(json_extract(metadata, '$.migrant'), 0) != 1",
        (run_id,)).fetchone()
    return int(row["n"] or 0), int(row["d"] or 0)


def compare(conn: sqlite3.Connection, baseline: List[str],
            treatment: List[str]) -> Dict[str, Any]:
    """
    Pool two sets of runs and report the ratio between them.

    Pooled rather than averaged per run because the quantity is already a
    ratio: averaging per-run ratios weights a 3-request run the same as a
    30-request one, and short runs are exactly where the noise is.
    """
    def pooled(run_ids: List[str]) -> Dict[str, Any]:
        parts = [measure(conn, r) for r in run_ids]
        totals: Dict[str, Any] = {"runs": run_ids}
        for key in ("mutation_requests", "generated_candidates", "distinct_generated",
                    "extra_offspring", "rejected_duplicates", "candidates"):
            totals[key] = sum(int(p[key] or 0) for p in parts)
        reqs = totals["mutation_requests"]
        # Distinctness is summed per run rather than recomputed across runs:
        # two runs from the same seed legitimately rediscover the same program,
        # and calling the second one a duplicate would punish reproducibility.
        totals["candidates_per_request"] = (
            round(totals["generated_candidates"] / reqs, 3) if reqs else None)
        totals["useful_candidates_per_request"] = (
            round(totals["distinct_generated"] / reqs, 3) if reqs else None)
        return totals

    a, b = pooled(baseline), pooled(treatment)
    verdict = _verdict(a, b)
    return {"baseline": a, "treatment": b, "verdict": verdict}


# Below this many requests per arm, the ratio is noise wearing a decimal point.
MIN_REQUESTS_PER_ARM = 10


def _verdict(baseline: Dict[str, Any], treatment: Dict[str, Any]) -> str:
    ra = baseline["mutation_requests"]
    rb = treatment["mutation_requests"]
    if min(ra, rb) < MIN_REQUESTS_PER_ARM:
        return (f"insufficient evidence: {ra} and {rb} mutation requests "
                f"(need {MIN_REQUESTS_PER_ARM} per arm). Do not conclude from this.")

    ua = baseline["useful_candidates_per_request"] or 0.0
    ub = treatment["useful_candidates_per_request"] or 0.0
    if ua <= 0:
        return "the baseline produced no useful candidates; nothing to compare."

    ratio = ub / ua
    raw_a = baseline["candidates_per_request"] or 0.0
    raw_b = treatment["candidates_per_request"] or 0.0
    raw_ratio = (raw_b / raw_a) if raw_a else 0.0

    if ratio < 1.1:
        return (f"no useful-yield gain: {ua:.2f} → {ub:.2f} distinct candidates "
                f"per request ({ratio:.2f}x), while raw yield moved "
                f"{raw_ratio:.2f}x. The extra candidates are duplicates.")
    return (f"useful yield {ratio:.2f}x ({ua:.2f} → {ub:.2f} distinct candidates "
            f"per request); raw yield {raw_ratio:.2f}x. The gap between the two "
            f"is duplicate output.")
